import type MaterialIcons from '@expo/vector-icons/MaterialIcons';
import type { SFSymbol } from 'expo-symbols';
import type { ComponentProps } from 'react';

type MaterialIcon = ComponentProps<typeof MaterialIcons>['name'];

/**
 * Uygulamadaki ikonlar: iOS'ta SF Symbols, Android'de (ve web'de) Material Icons karşılığı.
 * Yeni bir SF Symbol kullanılacaksa önce buraya eklenir; `AppSymbol` tipi eşlemesi olmayan ikonu derlemede yakalar.
 * Material Icons'ta dolu hâl varsayılan, boş hâl `-border`/`-outline` ekiyle (beğeni, kaydet ayırt edilsin).
 * Android alışkanlıkları gözetildi: paylaş simgesi `share`, geri `arrow-back`, taşma menüsü `more-vert`.
 */
export const ANDROID_ICONS = {
  // Gezinme ve genel
  'chevron.left': 'arrow-back',
  'chevron.right': 'chevron-right',
  'chevron.down': 'expand-more',
  xmark: 'close',
  'xmark.circle.fill': 'cancel',
  checkmark: 'check',
  'checkmark.circle': 'check-circle-outline',
  'checkmark.circle.fill': 'check-circle',
  circle: 'radio-button-unchecked',
  plus: 'add',
  'plus.circle': 'add-circle-outline',
  ellipsis: 'more-vert',
  'ellipsis.circle': 'more-vert',
  magnifyingglass: 'search',
  'square.and.arrow.up': 'share',
  'square.and.arrow.down': 'file-download',
  'arrow.up.right': 'north-east',
  'arrow.up.arrow.down': 'swap-vert',
  'arrow.up.circle.fill': 'arrow-circle-up',
  'arrow.up.left.and.arrow.down.right': 'open-in-full',
  'arrow.uturn.backward': 'undo',
  'list.bullet': 'format-list-bulleted',
  'list.bullet.below.rectangle': 'view-agenda',
  'list.star': 'list-alt',
  gear: 'settings',
  gearshape: 'settings',
  'info.circle': 'info-outline',
  'lock.fill': 'lock',
  eye: 'visibility',
  'eye.slash': 'visibility-off',
  link: 'link',
  'doc.on.clipboard': 'content-paste',
  'doc.text.fill': 'description',
  'trash.fill': 'delete',
  'wifi.exclamationmark': 'wifi-off',
  sparkles: 'auto-awesome',
  globe: 'language',
  at: 'alternate-email',
  'envelope.fill': 'email',
  phone: 'phone',
  'iphone.radiowaves.left.and.right': 'vibration',
  'checkmark.shield.fill': 'verified-user',
  'hand.raised': 'pan-tool',
  'hand.raised.fill': 'pan-tool',
  'hand.thumbsup.fill': 'thumb-up',
  'hand.thumbsdown.fill': 'thumb-down',
  pencil: 'edit',
  trash: 'delete-outline',
  flag: 'flag',
  nosign: 'block',
  'star.slash': 'star-border',
  'arrow.up.right.square': 'open-in-new',
  'rectangle.portrait.on.rectangle.portrait': 'amp-stories',
  'photo.on.rectangle': 'photo-library',

  // Sekmeler ve sosyal
  house: 'home',
  'house.fill': 'home',
  person: 'person-outline',
  'person.fill': 'person',
  'person.2': 'people-outline',
  'person.2.fill': 'people',
  'person.badge.plus': 'person-add',
  'person.fill.badge.plus': 'person-add',
  'person.crop.circle.badge.plus': 'person-add',
  'person.crop.circle.badge.checkmark': 'how-to-reg',
  heart: 'favorite-border',
  'heart.fill': 'favorite',
  bookmark: 'bookmark-border',
  'bookmark.fill': 'bookmark',
  'bubble.left': 'chat-bubble-outline',
  'bubble.left.fill': 'chat-bubble',
  'bubble.right': 'chat-bubble-outline',
  'text.bubble.fill': 'chat',
  message: 'sms',
  'message.fill': 'sms',
  'paperplane.fill': 'send',
  bell: 'notifications-none',
  'bell.fill': 'notifications',
  'bell.badge.fill': 'notifications-active',
  tag: 'local-offer',
  trophy: 'emoji-events',
  'trophy.fill': 'emoji-events',
  star: 'star-border',
  'star.fill': 'star',
  'graduationcap.fill': 'school',
  calendar: 'calendar-today',
  camera: 'photo-camera',
  photo: 'photo',
  'square.fill.on.square.fill': 'collections',
  'music.note': 'music-note',
  'play.rectangle': 'smart-display',

  // Harita ve yol tarifi
  map: 'map',
  'map.fill': 'map',
  'mappin.and.ellipse': 'place',
  'location.fill': 'near-me',
  'location.north.fill': 'navigation',
  'building.2': 'location-city',
  'arrow.triangle.turn.up.right.diamond.fill': 'directions',
  'figure.walk': 'directions-walk',
  'car.fill': 'directions-car',
  'tram.fill': 'tram',
  'flag.checkered': 'sports-score',
  'speaker.wave.2.fill': 'volume-up',
  'speaker.slash.fill': 'volume-off',

  // Mutfaklar, öğünler, rozetler
  'fork.knife': 'restaurant',
  'fork.knife.circle': 'restaurant-menu',
  flame: 'local-fire-department',
  'flame.fill': 'local-fire-department',
  fish: 'set-meal',
  'fish.fill': 'set-meal',
  wineglass: 'wine-bar',
  'wineglass.fill': 'wine-bar',
  mug: 'sports-bar',
  oven: 'outdoor-grill',
  'cup.and.saucer': 'local-cafe',
  'takeoutbag.and.cup.and.straw': 'fastfood',
  'birthday.cake': 'cake',
  leaf: 'eco',
  basket: 'shopping-basket',
  snowflake: 'ac-unit',
  'globe.asia.australia': 'public',
  'globe.europe.africa': 'public',
  'sun.horizon': 'wb-twilight',
  'sun.horizon.fill': 'wb-twilight',
  sunrise: 'free-breakfast',
  'sun.max': 'wb-sunny',
  sunset: 'dinner-dining',
  'moon.stars': 'bedtime',
} as const satisfies Partial<Record<SFSymbol, MaterialIcon>>;

/** Uygulamada kullanılabilen ikon adları (SF Symbol adı; Android karşılığı yukarıda) */
export type AppSymbol = keyof typeof ANDROID_ICONS;
